version: '2'

services: 
  bbps:
    build: .
    image: shintech/backbone_postgres_seed:latest
    container_name: bbps
    network_mode: bridge
    env_file:
      - ./bbps.env
    external_links:
      - postgres  
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: always
