version: '3'

services: 
  bbps:
    build: .
    image: shintech/backbone_postgres_seed:latest
    container_name: bbps
    env_file:
      - ./bbps.env
    links:
      - db       
    ports:
      - 8000:8000
    restart: always
  db:
    image: shintech/database:latest
    container_name: bbps_db
networks:
  default:
    external:
      name: dockernet