version: '2'

services: 
  bbps:
    build: .
    image: shintech/backbone_postgres_seed:latest
    container_name: bbps
    env_file:
      - ./bbps.env
    external_links:
      - postgres  
    ports:
      - 8000:8000
    restart: always
    networks:
      default:
        ipv4_address: 192.168.0.3
networks:
  default:
    external:
      name: shintech